export { default as Calendar } from './calendar/calendar';
export { default as Chats } from './chats';
export { default as Learning } from './learning';
export { default as Login } from './login';
export { default as Reports } from './reports';
export { default as PageNotFound } from './404';
export { default as Home } from './home';
export { default as Files } from './files';
export { default as Profile } from './profile';
